name: setup-node
description: https://github.com/actions/setup-node
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn

    - shell: bash
      run: yarn --immutable
