version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:lts

jobs:
  check-cache:
    executor: node
    steps:
      - checkout
      - run: yarn install --immutable --immutable-cache --check-cache

  lint:
    executor: node
    steps:
      - checkout
      - run: yarn lint

  test:
    executor: node
    steps:
      - checkout
      - run: yarn test:coverage

  prepack:
    executor: node
    steps:
      - checkout
      - run: yarn prepack

workflows:
  version: 2
  default:
    jobs:
      - check-cache
      - lint
      - test
      - prepack
