version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run: yarn install --frozen-lockfile --no-progress
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  test:
    executor: node
    steps:
      - attach_workspace: { "at": "." }
      - run: yarn test:coverage

  prepack:
    executor: node
    steps:
      - attach_workspace: { "at": "." }
      - run: yarn prepack

workflows:
  version: 2
  default:
    jobs:
      - install
      - test:
          requires:
            - install
      - prepack:
          requires:
            - install
