#!/usr/bin/env bash
set -e

#
# Helpers
##################################################

red="\e[31m"
reset="\e[39m"

run() {
  task=${1}
  shift
  echo -e [${task}] ${@}
  ${@}
}

fail() {
  echo -e ${red}${@}${reset}
  exit 1
}

#
# Commands
##################################################

dist=dist
pluginDist=plugins/verdaccio-github-oauth-ui

#
# Build server, config and client
#
build() {
  run build node rollup.js
  run build cp -R src/client/*.css $dist/public/
}

#
# Remove the plugin from node_modules
#
clean() {
  run clean rm -rf $dist
}

#
# Copy the built plugin to node_modules
#
copy() {
  run link mkdir -p $pluginDist/
  run link cp -R dist $pluginDist/
  run link cp package.json $pluginDist/
}

#
# Run linters
#
lint() {
  yarn tsc -p src/cli/tsconfig.json
  yarn tsc -p src/client/tsconfig.json
  yarn tsc -p src/server/tsconfig.json
  yarn tsc -p test/tsconfig.json
  yarn tslint -p src/cli/tsconfig.json ${@}
  yarn tslint -p src/client/tsconfig.json ${@}
  yarn tslint -p src/server/tsconfig.json ${@}
  yarn tslint -p test/tsconfig.json ${@}
}

whoami() {
  npm whoami --registry http://localhost:4873
}

test-publish() {
  packageName="0.0.0-$(date +%Y%m%d%H%M%S)"
  directory="package/$packageName"
  mkdir -p "$directory"
  echo "{\"name\":\"oauth-cli-test\",\"version\":\"$packageName\",\"license\":\"UNLICENSED\"}" > "$directory/package.json"
  cd "$directory"
  npm publish --registry http://localhost:4873
}

test-cli() {
  yarn node ./$dist/cli.js --registry http://localhost:4873
  publish
}

test-docker() {
  docker rm --force verdaccio || true
  docker build --tag verdaccio .
  docker run --publish 4873:4873 --name verdaccio verdaccio
}

#
# CLI
##################################################

#
# Call the function specified by the first parameter, passing all remaining
# parameters to the function. If no such function exists, display usage info.
#
if [ -n "$1" ] && type $1 | grep -i function > /dev/null; then
  command="$1"
  shift
  $command ${@}
else
  fail "No such command: $1"
fi
